### ISSUE TITLE
Link to presentation on Youtube

### ISSUE THREAD

**Issue by Yuri-SN** [hanagantig/goro#15]
Maybe should add link to Youtube video?

Архитектура Go проекта на практике - https://www.youtube.com/watch?v=hDwqFRUuykQ

**Comment by hanagantig** [comment]
Hi @Yuri-SN. Thanks for your suggestion.
Yes it will be very helpful.
Could you please add the youtube link to README then ?

**Comment by Yuri-SN** [comment]
Added to https://github.com/hanagantig/goro/pull/14
